# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('publication_date', models.DateField()),
                ('summary', models.CharField(max_length=5000)),
                ('article_image', models.CharField(max_length=100)),
                ('article_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=250)),
                ('number_of_articles', models.PositiveIntegerField()),
                ('views', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='Section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Section'),
        ),
    ]
